apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Recycle
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data
    server: 192.168.99.100
    readOnly: false