apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data2
    server: 192.168.99.100
    readOnly: false