kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-cliam-nfs2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  # volumeMode: Filesystem
  volumeName: pv-nfs2
  
  # selector:
  #   matchLabels:
  #     name: "pv-nfs2"
    # matchExpressions:
    #   - {key: environment, operator: In, values: [dev]}