#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: amitrepo/hello2java:0.0.1
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   exec:
        #     command:
        #     - cat
        #     - /myapp/app.jar
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello-app-srv
  labels:
    app: hello-app-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: hello-app
    targetPort: 8080
    nodePort: 31008
  selector:
    app: hello-app

