apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    # - ReadWriteOnce
    - ReadWriteMany
  # persistentVolumeReclaimPolicy: Recycle 
  persistentVolumeReclaimPolicy: Retain   ## data will present in shared dir even after pv/pvc deleted
  storageClassName: nfs
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  nfs:
    path: /data2
    server: 192.168.99.100
    readOnly: false