#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nodejs
spec:
  selector:
    matchLabels:
      app: hello-nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      containers:
      - name: hello-nodejs
        image: amitrepo/hello2nodejs:0.0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello-nodejs-srv
  labels:
    app: hello-nodejs-srv
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: hello-nodejs
    targetPort: 3000
    nodePort: 31007
  selector:
    app: hello-nodejs
  
  
