#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nodejs
spec:
  selector:
    matchLabels:
      app: hello-nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-nodejs
    spec:
      containers:
      - name: hello-nodejs
        image: amitrepo/hello2nodejs:0.0.1
        ports:
        - containerPort: 3000
