apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello-nodejs-srv
  labels:
    app: hello-nodejs-srv
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: hello-nodejs
    targetPort: 3000
    nodePort: 31007
  selector:
    app: hello-nodejs
