replicaCount: 1

image:
  containerPort: 8080

service:
  port: 8080
  targetPort: 8080
  nodePort: 31006

mongodb:
  host: mongodb
  port: "27017"
  database: helo4
  username: helo
  password: helo123

