apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "inventory-service.fullname" . }}-srv
  labels:
    app: hello-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: {{ template "inventory-service.fullname" . }}
    targetPort: 8080
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ template "inventory-service.fullname" . }}
