apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: edg01-mongodb:4.4.1
        env:
          - name: MONGODB_ROOT_PASSWORD 
            value: root1234
        securityContext:
          runAsUser: 1002
          #runAsGroup: 1002
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 3306
