apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: mariadb-srv
  labels:
    app: mariadb-srv
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    name: mariadb
    targetPort: 3306
    nodePort: 31009
  selector:
    app: mariadb
