apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello2-srv
  labels:
    app: hello2-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: hello2
    targetPort: 8080
    nodePort: 31006
  selector:
    app: hello2
