apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hello-app-srv
  labels:
    app: hello-app-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    name: hello-app
    targetPort: 8080
    nodePort: 31008
  selector:
    app: hello-app
