kind: ConfigMap
apiVersion: v1
metadata:
  name: assets 
data:
  application.yml:   |
    spring:
      data:
        mongodb:
          host: mongodb
          port: 27017
          authentication-database: helo4
          database: helo4
          username: helo
          password: helo123
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: assets-srv
  labels:
    app: assets-srv
spec:
  type: LoadBalancer
  ports:
  - port: 8080 
    name: assets
    targetPort: 8080
    nodePort: 31006
  selector:
    app: assets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
spec:
  selector:
    matchLabels:
      app: assets 
  replicas: 1
  template:
    metadata:
      labels:
        app: assets
      annotations:
        configmap.reloader.stakater.com/reload: "config"
    spec:
      containers:
      - name: assets
        image: "amitrepo/hello2java:0.0.1"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: config
            mountPath: /config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: assets
            items:
              - key: application.yml
                path: application.yml

