apiVersion: apps/v1 
kind: Deployment
metadata:
  name: hello1
spec:
  selector:
    matchLabels:
      app: hello1
  replicas: 1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - name: hello1
        image: amitrepo/hello2java:0.0.1
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/data"
          name: pvc-cliam-nfs-1
      volumes:
      - name: pvc-cliam-nfs-1
        persistentVolumeClaim:
          claimName: pvc-cliam-nfs-1
